// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXsXdbzioHCAVb4IMNbSAZjHtSjoE7Z6g',
    appId: '1:483053949396:web:3e23b384251be352334641',
    messagingSenderId: '483053949396',
    projectId: 'blooming-petal-1',
    authDomain: 'blooming-petal-1.firebaseapp.com',
    storageBucket: 'blooming-petal-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIutGSsHgPbIzCTYRf8lF1ImpJpV_1FDA',
    appId: '1:483053949396:android:c49e1409f3bf8b9f334641',
    messagingSenderId: '483053949396',
    projectId: 'blooming-petal-1',
    storageBucket: 'blooming-petal-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVs-NybTdoaTJClgIXCuTxlx7C_U461kg',
    appId: '1:483053949396:ios:a9f7d64f3282fd58334641',
    messagingSenderId: '483053949396',
    projectId: 'blooming-petal-1',
    storageBucket: 'blooming-petal-1.firebasestorage.app',
    iosBundleId: 'com.example.bloomingPetalApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVs-NybTdoaTJClgIXCuTxlx7C_U461kg',
    appId: '1:483053949396:ios:a9f7d64f3282fd58334641',
    messagingSenderId: '483053949396',
    projectId: 'blooming-petal-1',
    storageBucket: 'blooming-petal-1.firebasestorage.app',
    iosBundleId: 'com.example.bloomingPetalApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXsXdbzioHCAVb4IMNbSAZjHtSjoE7Z6g',
    appId: '1:483053949396:web:4c8874e19ab0f524334641',
    messagingSenderId: '483053949396',
    projectId: 'blooming-petal-1',
    authDomain: 'blooming-petal-1.firebaseapp.com',
    storageBucket: 'blooming-petal-1.firebasestorage.app',
  );
}
